# Group 1
# Done by:
# - Abdullah Hanoosh, Student ID: 100749026
# - Malyka Sardar, Student ID: 100752640
# - Marwan Alam, Student ID: 100842087
# - Vidurshan Sribalasuhabiramam, Student ID: 100558257


all: myshell

myshell: myshell.c utility.c
	gcc -Wall -o myshell myshell.c utility.c -I.
	
clean:
	rm -f myshell
